# TCL File Generated by Component Editor 18.1
# Fri Oct 02 09:35:02 MSK 2020
# DO NOT MODIFY


# 
# ams_spi_bridge "Avalon-MM to SPI bridge" v1.0
# Bolnov Evgeniy 2020.10.02.09:35:02
# Avalon-MM to SPI bridge
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ams_spi_bridge
# 
set_module_property DESCRIPTION "Avalon-MM to SPI bridge"
set_module_property NAME ams_spi_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Bridges and Adaptors/Memory Mapped"
set_module_property AUTHOR "Bolnov Evgeniy"
set_module_property DISPLAY_NAME "Avalon-MM to SPI bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ams_spi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ams_spi.sv SYSTEM_VERILOG PATH ../rtl/ams_spi.sv TOP_LEVEL_FILE
add_fileset_file ams_spi.sdc SDC PATH ../rtl/ams_spi.sdc


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME "Разрядность адреса"
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS Bits
set_parameter_property ADDR_WIDTH ALLOWED_RANGES 0:128
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter SS_COUNT INTEGER 2
set_parameter_property SS_COUNT DEFAULT_VALUE 2
set_parameter_property SS_COUNT DISPLAY_NAME "Количество ведомых"
set_parameter_property SS_COUNT TYPE INTEGER
set_parameter_property SS_COUNT UNITS None
set_parameter_property SS_COUNT ALLOWED_RANGES 0:8
set_parameter_property SS_COUNT HDL_PARAMETER true
add_parameter CLOCK_FREQ INTEGER 0 CLOCK_RATE
set_parameter_property CLOCK_FREQ DEFAULT_VALUE 0
set_parameter_property CLOCK_FREQ DISPLAY_NAME "Частота Avalon-MM"
set_parameter_property CLOCK_FREQ TYPE INTEGER
set_parameter_property CLOCK_FREQ UNITS Hertz
set_parameter_property CLOCK_FREQ ALLOWED_RANGES 0:250000000
set_parameter_property CLOCK_FREQ DESCRIPTION CLOCK_RATE
set_parameter_property CLOCK_FREQ HDL_PARAMETER true
set_parameter_property CLOCK_FREQ SYSTEM_INFO_TYPE CLOCK_RATE
set_parameter_property CLOCK_FREQ SYSTEM_INFO_ARG main_clk
add_parameter SPI_CLOCK INTEGER 50000000
set_parameter_property SPI_CLOCK DEFAULT_VALUE 50000000
set_parameter_property SPI_CLOCK DISPLAY_NAME "Частота SPI"
set_parameter_property SPI_CLOCK TYPE INTEGER
set_parameter_property SPI_CLOCK UNITS Hertz
set_parameter_property SPI_CLOCK ALLOWED_RANGES 0:100000000
set_parameter_property SPI_CLOCK HDL_PARAMETER true
add_parameter READ_TIMEOUT INTEGER 60
set_parameter_property READ_TIMEOUT DEFAULT_VALUE 60
set_parameter_property READ_TIMEOUT DISPLAY_NAME READ_TIMEOUT
set_parameter_property READ_TIMEOUT TYPE INTEGER
set_parameter_property READ_TIMEOUT UNITS None
set_parameter_property READ_TIMEOUT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READ_TIMEOUT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ams
# 
add_interface ams avalon end
set_interface_property ams addressUnits WORDS
set_interface_property ams associatedClock main_clk
set_interface_property ams associatedReset main_reset
set_interface_property ams bitsPerSymbol 8
set_interface_property ams burstOnBurstBoundariesOnly false
set_interface_property ams burstcountUnits WORDS
set_interface_property ams explicitAddressSpan 0
set_interface_property ams holdTime 0
set_interface_property ams linewrapBursts false
set_interface_property ams maximumPendingReadTransactions 200
set_interface_property ams maximumPendingWriteTransactions 0
set_interface_property ams readLatency 0
set_interface_property ams readWaitTime 1
set_interface_property ams setupTime 0
set_interface_property ams timingUnits Cycles
set_interface_property ams writeWaitTime 0
set_interface_property ams ENABLED true
set_interface_property ams EXPORT_OF ""
set_interface_property ams PORT_NAME_MAP ""
set_interface_property ams CMSIS_SVD_VARIABLES ""
set_interface_property ams SVD_ADDRESS_GROUP ""

add_interface_port ams ams_address address Input ADDR_WIDTH
add_interface_port ams ams_writedata writedata Input 32
add_interface_port ams ams_readdata readdata Output 32
add_interface_port ams ams_write write Input 1
add_interface_port ams ams_read read Input 1
add_interface_port ams ams_readdatavalid readdatavalid Output 1
add_interface_port ams ams_waitrequest waitrequest Output 1
add_interface_port ams ams_response response Output 2
set_interface_assignment ams embeddedsw.configuration.isFlash 0
set_interface_assignment ams embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ams embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ams embeddedsw.configuration.isPrintableDevice 0


# 
# connection point main_clk
# 
add_interface main_clk clock end
set_interface_property main_clk clockRate 0
set_interface_property main_clk ENABLED true
set_interface_property main_clk EXPORT_OF ""
set_interface_property main_clk PORT_NAME_MAP ""
set_interface_property main_clk CMSIS_SVD_VARIABLES ""
set_interface_property main_clk SVD_ADDRESS_GROUP ""

add_interface_port main_clk main_clk clk Input 1


# 
# connection point main_reset
# 
add_interface main_reset reset end
set_interface_property main_reset associatedClock main_clk
set_interface_property main_reset synchronousEdges DEASSERT
set_interface_property main_reset ENABLED true
set_interface_property main_reset EXPORT_OF ""
set_interface_property main_reset PORT_NAME_MAP ""
set_interface_property main_reset CMSIS_SVD_VARIABLES ""
set_interface_property main_reset SVD_ADDRESS_GROUP ""

add_interface_port main_reset main_reset reset Input 1


# 
# connection point SPI
# 
add_interface SPI conduit end
set_interface_property SPI associatedClock main_clk
set_interface_property SPI associatedReset main_reset
set_interface_property SPI ENABLED true
set_interface_property SPI EXPORT_OF ""
set_interface_property SPI PORT_NAME_MAP ""
set_interface_property SPI CMSIS_SVD_VARIABLES ""
set_interface_property SPI SVD_ADDRESS_GROUP ""

add_interface_port SPI MISO miso Input 1
add_interface_port SPI MOSI mosi Output 1
add_interface_port SPI SCLK sclk Output 1
add_interface_port SPI nSS nss Output SS_COUNT

